"use strict";
var message = ("Hey Abu Hurairah,I have started learning TYPESCRIPT");
console.log(message);
var Name = ("Abu Hurairah");
console.log(Name);
var userName = ("num");
var num1 = (10);
var num2 = (20);
var num3 = (30);
var num4 = (40);
var num5 = (50);
var num6 = (60);
var num7 = (70);
var num8 = (80);
var num9 = (90);
var num10 = (100);
var adding = (num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10);
var subtraction = (num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10);
var multiplying = (num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10);
var division = (num1 % num5);
console.log(adding);
console.log(subtraction);
console.log(multiplying);
console.log(division);
